import {writeWallProjects} from './wall-projects.mjs';
import {photoAlbum} from './photography-template.mjs';
import {deskTemplate} from './desk-template.mjs';
import fs from 'node:fs';
import path from 'node:path';
const content=JSON.parse(fs.readFileSync('content.json','utf8'));
writeWallProjects(content);
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const t=(en,zh,tag='span',attrs='')=>`<${tag} data-en="${esc(en)}" data-zh="${esc(zh)}" ${attrs}>${esc(en)}</${tag}>`;
const intro=content.site.intro;
content.projects.sort((a,b)=>Number(b.year)-Number(a.year));
content.writing.sort((a,b)=>Number(a.date)-Number(b.date));
const sortControl=(id,order)=>`<div class="collection-sort"><label for="${id}-sort">${t('Sort by','排序')}</label><select id="${id}-sort" data-sort-target="${id}">${t('Newest first','最新在前','option',`value="newest" ${order==='newest'?'selected':''}`)}${t('Oldest first','最旧在前','option',`value="oldest" ${order==='oldest'?'selected':''}`)}</select></div>`;
const nav=[['/','HOME','首页'],['/projects/','PROJECTS','项目'],['/writing/','WRITING','写作'],['/about/','ABOUT','关于']];
const link=(href,en,zh,attrs='')=>t(en,zh,'a',`href="${href}" ${attrs}`);
function shell(title,active,body){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)} — Weiyi Wang</title><meta name="description" content="${esc(intro[0])}"><link rel="icon" href="/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/desk.css"><script defer src="/app.js"></script>${active==='HOME'?'<link rel="stylesheet" href="/desk-intro.css"><script src="/desk-intro.js"></script>':''}</head><body data-page-en="${esc(title)}">${active==='HOME'?'<link rel="stylesheet" href="/home-editorial.css">':''}<a class="skip" href="#main">Skip to content / 跳至内容</a><header><a class="wordmark" href="${active==='HOME'?'/about/':'/'}">WEIYI WANG${active==='HOME'?'<span class="identity-line">ARCHITECTURE × TECHNOLOGY</span>':''}</a><nav aria-label="Main navigation">${nav.map(([url,en,zh])=>link(url,en,zh,active===en?'aria-current="page"':'')).join('')}</nav><div class="language" role="group" aria-label="Language / 语言"><button data-lang="en" aria-pressed="true" lang="en">EN</button><span>/</span><button data-lang="zh" aria-pressed="false" lang="zh-CN">中文</button></div></header><main id="main">${body}</main><footer><div><span class="footer-location">LONDON <span class="coordinates">51.5074° N &nbsp; 0.1278° W</span></span></div><div class="footer-links">${link('/other-work/','Other Work ↗︎','其他创作 ↗︎')}${link('/cv/','CV','履历')}${link('/about/','About','关于')}</div><span class="copyright">© ${new Date().getFullYear()} Weiyi Wang</span></footer></body></html>`;}
function media(p,cls=''){return p.cover?`<div class="project-image ${cls}"><img src="${esc(p.cover)}" alt="${esc(p.coverAlt||p.name)}" loading="lazy" width="1600" height="1000"></div>`:`<div class="project-image image-pending ${cls}"><span class="image-number">${String(content.projects.indexOf(p)+1).padStart(2,'0')} / ${esc(p.name)}</span>${t('Project image forthcoming','项目图片待补充','span','class="pending-caption"')}<span class="image-cross" aria-hidden="true">+</span></div>`;}
function projectLink(p,i){return `<article class="project project-${i+1}" data-year="${esc(p.year||0)}"><a class="project-link" href="/projects/${p.slug}/">${media(p)}<div class="project-caption"><h3>${esc(p.name)}<span aria-hidden="true">↗︎</span></h3><p>${t(...p.category)}${p.year?`<span class="year">${p.year}</span>`:''}</p></div></a></article>`;}
const pageHead=(label,title,zh,desc='',descZh='')=>`<div class="page-heading">${label?t(label,label,'p','class="eyebrow"'):''}${t(title,zh,'h1')}${desc?t(desc,descZh,'p','class="page-intro"'):''}</div>`;
const empty=(en,zh)=>t(en,zh,'p','class="empty-copy"');
function write(route,html){if(process.argv.includes('--content-only')&&!route)return;const dir=path.join('dist',route);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'index.html'),html);}
write('',shell('Home','HOME',deskTemplate(t,link)+`<section class="selected home-projects" id="projects" aria-labelledby="selected-title"><div class="section-heading">${t('Selected projects','项目选集','h2','id="selected-title"')}<span>${String(content.projects.length).padStart(2,'0')}</span></div><div class="editorial-grid">${content.projects.map(projectLink).join('')}</div></section>`));
write('projects',shell('Projects','PROJECTS',`${pageHead('','Projects','项目')}<section class="selected" id="projects" aria-labelledby="selected-title"><div class="section-heading">${t('Selected projects','项目选集','h2','id="selected-title"')}<span>${String(content.projects.length).padStart(2,'0')}</span></div>${sortControl('project-list','newest')}<div class="editorial-grid" id="project-list">${content.projects.map(projectLink).join('')}</div></section><div class="elsewhere">${link('/other-work/','OTHER WORK →','其他创作 →')}</div>`));
write('research', '<!doctype html><html lang="en"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=/"><title>Projects — Weiyi Wang</title></head><body><a href="/">Projects</a></body></html>');
write('writing',shell('Writing','WRITING',`<link rel="stylesheet" href="/media-viewer.css"><link rel="stylesheet" href="/content-refinements.css"><script defer src="/media-viewer.js"></script>${pageHead('','Writing','写作')}${sortControl('writing-list','oldest')}<section class="writing-list" id="writing-list">${content.writing.map(e=>`<article id="${esc(e.slug)}" data-year="${esc(e.date||0)}"><div class="writing-cover">${e.cover?`<a class="media-trigger" data-media="image" href="${esc(e.cover)}"><img src="${esc(e.cover)}" alt="${esc(e.coverAlt||e.title[0])}" loading="lazy" width="320" height="240"></a>`:t('Cover forthcoming','封面待补充')}</div><div class="writing-content"><p class="eyebrow">${esc(e.date||'')}</p>${t(...e.title,'h2')}${e.description?t(...e.description,'p'):''}${e.url?link(e.url,'Read PDF ↗︎','阅读 PDF ↗︎','class="publication-link" target="_blank" rel="noopener"'):''}${e.doi?link(e.doi,'DOI ↗︎','DOI ↗︎','class="publication-link doi-link" target="_blank" rel="noopener"'):''}${writingMedia(e)}</div></article>`).join('')}</section>`));
write('about',shell('About','ABOUT',`<link rel="stylesheet" href="/content-refinements.css">${pageHead('','About','关于')}<section class="about-profile"><div>${t('Weiyi Wang','WEIYI WANG','h2')}${content.site.about[0].split(/\n\s*\n/).map((en,i)=>t(en,content.site.about[1].split(/\n\s*\n/)[i]||'','p','class="prose"')).join('')}<div class="inline-links">${link('/cv/','CV →','履历 →')}</div></div><div class="about-portraits">${(content.site.photos||[content.site.photo]).filter(Boolean).map((src,i)=>`<figure class="about-portrait"><img src="${esc(src)}" alt="${src.includes('about-studio')?'Weiyi Wang working on an architectural model':'Weiyi Wang'}" loading="${i===0?'eager':'lazy'}"></figure>`).join('')}</div></section><section class="about-contact" aria-label="Contact"><div>${t('Contact','联系','h2')}<div class="contact-addresses"><a class="contact-email" href="mailto:${esc(content.site.contact.email)}">${esc(content.site.contact.email)} ↗︎</a>${t("Primary email","主要邮箱","span",'class="contact-primary"')}<a class="contact-email" href="mailto:${esc(content.site.contact.secondaryEmail)}">${esc(content.site.contact.secondaryEmail)} ↗︎</a>${link(content.site.contact.github,"GitHub ↗︎","GitHub ↗︎",'target="_blank" rel="noopener noreferrer"')}</div></div><div class="contact-social"><div>${link(content.site.contact.linkedin,'LinkedIn ↗︎','领英 ↗︎','target="_blank" rel="noopener noreferrer"')}<a href="/images/linkedin-qr.jpg" target="_blank" rel="noopener" aria-label="LinkedIn QR code"><img src="/images/linkedin-qr.jpg" alt="LinkedIn QR code" width="480" height="480" loading="lazy"></a></div><div>${link(content.site.contact.xiaohongshu,'Rednote ↗︎','小红书 ↗︎','target="_blank" rel="noopener noreferrer"')}<a href="/images/xiaohongshu-qr.jpg" target="_blank" rel="noopener" aria-label="Rednote QR code"><img src="/images/xiaohongshu-qr.jpg" alt="Rednote QR code" width="770" height="770" loading="lazy"></a></div></div></section><section class="about-practice">${t('Other work','其他创作','h2')}<div class="other-list">${[['Photography','摄影'],['Physical Models','手工模型'],['Film / Video','影像'],['Sketches','手绘'],['Visual Experiments','视觉实验']].map((x,i)=>`<section><span class="section-index">0${i+1}</span><div>${i<3?`<h2>${link(i===0?'/other-work/photography/':i===1?'/other-work/models/':'/other-work/film/',...x)}</h2>`:t(...x,'h2')}${i===0?t('A photographic notebook.','摄影手记。','p'):i===2?t('Project films and research videos.','作品影像与研究视频。','p'):i===1?t('Models and material studies.','模型与材料研究。','p'):empty('Collection forthcoming.','作品整理中。')}</div></section>`).join('')}</div></section>`));
write('other-work/film',shell('Film / Video','ABOUT',`<link rel="stylesheet" href="/media-viewer.css"><script defer src="/media-viewer.js"></script>${pageHead('','Film / Video','影像')}<section class="film-list">${(content.films||[]).map(f=>`<article><a class="media-trigger" data-media="video" href="${esc(f.src)}"><img src="${esc(f.poster)}" alt="${esc(f.title)}" loading="lazy"><span class="media-play">${t('Play film','播放视频')}</span></a><h2>${esc(f.title)}</h2><span class="film-duration">${esc(f.year)} · ${Math.floor(f.duration/60)}:${String(f.duration%60).padStart(2,'0')}</span><div class="film-links">${f.links.map(l=>link(l.url,...l.label)).join('')}</div></article>`).join('')}</section>`));
write('cv',shell('CV','ABOUT',`${pageHead('','Curriculum Vitae','个人履历','Weiyi Wang','WEIYI WANG')}<div class="cv-tools">${content.cvPdf?link(content.cvPdf,'Download CV ↗︎','下载履历 ↗︎','download'):t('Download CV ↗︎ — PDF forthcoming','下载履历 ↗︎ — PDF 待补充','span','class="muted"')}${t('CV transcript','履历全文','span','class="eyebrow"')}</div><link rel="stylesheet" href="/cv-carousel.css"><script defer src="/cv-carousel.js"></script><div class="cv-pages ${content.cvPreviews.length===1?'cv-single-page':''}"><div class="cv-carousel" role="region" aria-label="CV pages" tabindex="0">${content.cvPreviews.map((src,i)=>`<figure class="cv-preview"><a href="${esc(content.cvPdf)}#page=${i+1}" target="_blank" rel="noopener"><img src="${esc(src)}" alt="Weiyi Wang — CV page ${i+1}" width="1274" height="1800" loading="${i?"lazy":"eager"}"></a><figcaption>${link(content.cvPdf+"#page="+(i+1),"Open PDF — page "+(i+1),"打开 PDF — 第 "+(i+1)+" 页",'target="_blank" rel="noopener"')}</figcaption></figure>`).join('')}</div>${content.cvPreviews.length>1?`<div class="cv-scroll-controls"><span>${t("Swipe left to view page 2","向左滑动查看第 2 页")}</span><button type="button" data-cv-scroll="-1" aria-label="Previous CV page">←</button><button type="button" data-cv-scroll="1" aria-label="Next CV page">→</button></div>`:""}</div><div class="cv-record">${content.cv.map((s,i)=>`<section class="cv-section"><div><span class="section-index">0${i+1}</span>${t(...s.title,'h2')}</div><div>${s.entries.length?s.entries.map(cvEntry).join(''):empty('Details forthcoming.','信息待补充。')}</div></section>`).join('')}</div>`));
write('other-work',shell('Other Work','',`${pageHead('ELSEWHERE','Other Work','其他创作','Observations and creative practice beyond the projects.','项目之外的观察与创作。')}<div class="other-list">${[['Photography','摄影'],['Physical Models','手工模型'],['Film / Video','影像'],['Sketches','手绘'],['Visual Experiments','视觉实验']].map((x,i)=>`<section><span class="section-index">0${i+1}</span><div>${i<2?`<h2>${link(i===0?'/other-work/photography/':'/other-work/models/',...x)}</h2>`:t(...x,'h2')}${i===0?t('A photographic notebook.','摄影手记。','p'):i===1?t('Models and material studies.','模型与材料研究。','p'):empty('Collection forthcoming.','作品整理中。')}</div></section>`).join('')}</div>`));
function renderBlock(s){if(s.type==='group')return s.blocks.map(renderBlock).join('');if(s.type==='gallery'&&s.images?.length)return `<div class="drawing-gallery">${s.images.map(im=>`<figure><a href="${esc(im.src)}" target="_blank" rel="noopener"><img src="${esc(im.src)}" alt="${esc(im.alt)}" loading="lazy"></a>${im.caption?t(...im.caption,'figcaption'):''}</figure>`).join('')}</div>`;if(s.type==='video'&&s.src)return `<video controls preload="metadata" ${s.poster?`poster="${esc(s.poster)}"`:''}><source src="${esc(s.src)}">${t('Your browser does not support this video.','你的浏览器不支持此视频。')}</video>`;return s.text?t(...s.text,'p','class="prose"'):empty(s.type==='gallery'?'Visual documentation forthcoming.':'Project documentation forthcoming.',s.type==='gallery'?'图像记录待补充。':'项目说明待补充。');}
content.projects.forEach((p,i)=>write(`projects/${p.slug}`,shell(p.name,'PROJECTS',`<div class="project-top">${link('/projects/','← Selected Work','← 返回作品选集')}<span>${t(...p.category)}${p.year?' · '+p.year:''}</span></div><div class="project-title"><h1>${esc(p.name)}</h1>${p.subtitle?t(...p.subtitle,'p','class="project-subtitle"'):''}</div>${media(p,'detail-cover')}${p.heroMotion?`<div class="project-motion"><video autoplay muted loop playsinline controls preload="metadata" poster="${esc(p.heroMotion.poster)}" aria-label="${esc(p.name)} motion cover"><source src="${esc(p.heroMotion.src)}" type="video/mp4"></video></div>`:''}<div class="project-document"><aside>${t('In this project','项目内容','p','class="eyebrow"')}<nav aria-label="Project sections">${p.sections.map((s,j)=>link(`#section-${j}`,...s.title)).join('')}</nav></aside><div>${p.sections.map((s,j)=>`<section class="document-section ${s.type}" id="section-${j}">${t(...s.title,'h2')}${renderBlock(s)}</section>`).join('')}</div></div>${(content.models||[]).filter(m=>m.project===p.slug).map(m=>`<div class="project-model-link" style="padding:30px 0;border-top:1px solid var(--line);font-size:18px">${link(`/other-work/models/#model-${m.slug}`,'View physical model: '+m.name,'查看实体模型：'+m.name)}</div>`).join('')}<div class="next-project">${link('/projects/','All projects','全部项目')}${link(`/projects/${content.projects[(i+1)%content.projects.length].slug}/`,'Next: '+content.projects[(i+1)%content.projects.length].name+' →','下一个：'+content.projects[(i+1)%content.projects.length].name+' →')}</div>`)));
fs.writeFileSync('dist/404.html',shell('Page not found','',`${pageHead('404','Page not found.','页面不存在。')}${link('/','Return to Selected Work →','返回作品选集 →')}`));
console.log('Built 11 pages and 404.');

if(!process.argv.includes('--content-only'))fs.writeFileSync('dist/desk-config.json',JSON.stringify(content.desk));


write('other-work/models',shell('Physical Models','ABOUT',pageHead('OTHER WORK','Physical Models','手工模型')+'<div class="model-collection">'+(content.models||[]).map(m=>`<section class="model-entry" id="model-${esc(m.slug)}" style="scroll-margin-top:120px"><p class="eyebrow">${esc(m.year)}</p><h2>${esc(m.name)}</h2>${modelCarousel(m)}${m.project?link('/projects/'+m.project+'/','View project: '+m.name+' →','查看项目：'+m.name+' →','class="model-project-link"'):''}</section>`).join('')+'</div>'));

function modelCarousel(m){return `<div class="model-carousel" role="region" aria-label="${esc(m.name)} photographs" tabindex="0">${m.images.map(im=>`<figure><a href="${esc(im.src)}" target="_blank" rel="noopener"><img src="${esc(im.src)}" alt="${esc(im.alt)}" loading="lazy"></a></figure>`).join("")}</div><div class="model-scroll-controls"><button type="button" data-model-scroll="-1" aria-label="Previous photograph">←</button><button type="button" data-model-scroll="1" aria-label="Next photograph">→</button></div>`;}

write('other-work/photography',shell('Photography','ABOUT',pageHead('','Photography','摄影')+photoAlbum(content.photography||[],t,esc)));

function cvEntry(e){const list=items=>items?.length?`<ul class="cv-bullets">${items.map(item=>t(...item,"li")).join("")}</ul>`:"";return `<article class="cv-entry">${e.date?`<span class="muted">${esc(e.date)}</span>`:""}${e.title?t(...e.title,"h3"):""}${e.organization?t(...e.organization,"p",'class="cv-organization"'):""}${e.description?t(...e.description,"p"):""}${list(e.bullets)}${e.outcomes?`${t("Research Outcomes:","研究成果：","h4")}${list(e.outcomes)}`:""}${e.url?link(e.url,e.url,e.url,'class="publication-link"'):""}</article>`;}

function writingMedia(e){const caption=e.slug==="memory-patterns"?["Mind map","思维导图"]:["Conference photographs","会议照片"];return `<div class="writing-media-row">${e.video?`<a class="writing-video media-trigger" data-media="video" href="${esc(e.video)}" data-caption-en="${esc(e.title[0])}" data-caption-zh="${esc(e.title[1])}"><img src="${esc(e.cover)}" alt="${esc(e.title[0])}" loading="lazy"><span class="media-play">${t("Play film","播放视频")}</span></a>`:""}${(e.images||[]).map(src=>`<a class="media-trigger" href="${esc(src)}" data-media="image" data-caption-en="${caption[0]}" data-caption-zh="${caption[1]}"><img src="${esc(src)}" alt="${caption[0]}" loading="lazy"></a>`).join("")}</div>`;}
